"""Server-side lead-capture copy (Phase 13.2).

These are picked by the orchestrator, never generated by the LLM, so contact
asks are deterministic and on-brand. Focused templates use {short_title}.
"""

from __future__ import annotations

import random

LEAD_OPENER_TEMPLATES_FOCUSED = [
    "Honestly, {short_title} sounds like the one you keep circling. Want me to have "
    "someone from the team walk you through the application and EMI options? They'll "
    "just need a quick way to reach you.",

    "You've been digging into {short_title} for a bit. A 15-minute call with the upGrad "
    "team would save you a lot of guessing. Drop your details and they'll loop in.",

    "Sounds like {short_title} is the front-runner. The fastest way to lock in eligibility "
    "and the EMI math is a quick chat with the program advisor. Want me to set that up?",

    "Since you're getting specific about {short_title}, this is usually the point where a "
    "quick call with the team helps more than I can. I can pass you over, just need your contact.",
]

LEAD_OPENER_TEMPLATES_GENERIC = [
    "You've been weighing these options for a while. At some point a human is better than "
    "I am for the next-step questions. Want me to have an upGrad advisor reach out?",

    "I'm useful for the matching part, less so once you're into application logistics. If "
    "you'd like, I can hand you to someone on the team who handles that end to end.",
]

LEAD_DECLINED_REPLIES = [
    "All good, no pressure. What else do you want to poke at?",
    "Cool, parked. If you change your mind, just say the word.",
    "No worries. Anything else you want to dig into?",
]

LEAD_CONFIRM_TEMPLATES = [
    "Got it, someone from the upGrad team will reach out within one business day. In the "
    "meantime, anything else you want to compare or dig into?",
    "Locked in. The team usually circles back within a day. Want to keep exploring while you wait?",
]


def pick_opener(short_title: str | None) -> str:
    if short_title:
        return random.choice(LEAD_OPENER_TEMPLATES_FOCUSED).format(short_title=short_title)
    return random.choice(LEAD_OPENER_TEMPLATES_GENERIC)


def pick_declined_reply() -> str:
    return random.choice(LEAD_DECLINED_REPLIES)


def pick_confirm() -> str:
    return random.choice(LEAD_CONFIRM_TEMPLATES)
